-- Event store of the postgresql-event-sourcing design: aggregates, immutable events, snapshots, subscriptions.
-- Events are only ever INSERTed; UPDATE and DELETE are not part of the model.

CREATE TABLE IF NOT EXISTS ES_AGGREGATE (
    ID             UUID    PRIMARY KEY,
    VERSION        INTEGER NOT NULL,
    AGGREGATE_TYPE TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_ES_AGGREGATE_AGGREGATE_TYPE ON ES_AGGREGATE (AGGREGATE_TYPE);

CREATE TABLE IF NOT EXISTS ES_EVENT (
    ID             BIGSERIAL PRIMARY KEY,
    TRANSACTION_ID XID8      NOT NULL,
    AGGREGATE_ID   UUID      NOT NULL REFERENCES ES_AGGREGATE (ID),
    VERSION        INTEGER   NOT NULL,
    EVENT_TYPE     TEXT      NOT NULL,
    JSON_DATA      JSON      NOT NULL,
    UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE INDEX IF NOT EXISTS IDX_ES_EVENT_TRANSACTION_ID_ID ON ES_EVENT (TRANSACTION_ID, ID);
CREATE INDEX IF NOT EXISTS IDX_ES_EVENT_AGGREGATE_ID ON ES_EVENT (AGGREGATE_ID);

CREATE TABLE IF NOT EXISTS ES_AGGREGATE_SNAPSHOT (
    AGGREGATE_ID UUID    NOT NULL REFERENCES ES_AGGREGATE (ID),
    VERSION      INTEGER NOT NULL,
    JSON_DATA    JSON    NOT NULL,
    PRIMARY KEY (AGGREGATE_ID, VERSION)
);

CREATE TABLE IF NOT EXISTS ES_EVENT_SUBSCRIPTION (
    SUBSCRIPTION_NAME   TEXT   PRIMARY KEY,
    LAST_TRANSACTION_ID XID8   NOT NULL,
    LAST_EVENT_ID       BIGINT NOT NULL
);
